[package]
name = "todo-list-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.todo-list]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.36.0"
